name: universal_breakpoints
description: "A simple, reusable, and platform-independent screen size breakpoints package for Flutter. Provides responsive design utilities for Android, iOS, Web, Windows, macOS, and Linux."
version: 1.0.0
homepage: https://github.com/shyamexe/universal_breakpoints
repository: https://github.com/shyamexe/universal_breakpoints
issue_tracker: https://github.com/shyamexe/universal_breakpoints/issues
documentation: https://shyamexe.github.io/universal_breakpoints/
publish_to: 'https://pub.dev'

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
# flutter:
#
#  # To add assets to your package, add an assets section, like this:
#  # assets:
#  #   - images/a_dot_burr.jpeg
#  #   - images/a_dot_ham.jpeg
#  #
#  # For details regarding assets in packages, see
#  # https://flutter.dev/to/asset-from-package
#  #
#  # An image asset can refer to one or more resolution-specific "variants", see
#  # https://flutter.dev/to/resolution-aware-images
#
#  # To add custom fonts to your package, add a fonts section here,
#  # in this "flutter" section. Each entry in this list should have a
#  # "family" key with the font family name, and a "fonts" key with a
#  # list giving the asset and other descriptors for the font. For
#  # example:
#  # fonts:
#  #   - family: Schyler
#  #     fonts:
#  #       - asset: fonts/Schyler-Regular.ttf
#  #       - asset: fonts/Schyler-Italic.ttf
#  #         style: italic
#  #   - family: Trajan Pro
#  #     fonts:
#  #       - asset: fonts/TrajanPro.ttf
#  #       - asset: fonts/TrajanPro_Bold.ttf
#  #         weight: 700
#  #
#  # For details regarding fonts in packages, see
#  # https://flutter.dev/to/font-from-package
